name: pymc_bda
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.11
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - seaborn
  - statsmodels
  - pymc
  - pip
  - pip:
      - arviz[all]